services:
  orders-db:
    container_name: delivery_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=testHelisa
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=deliverydb